version: '2.27'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: clothes-web-shop

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: clothes-web-shop
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-with-charset.sh:/docker-entrypoint-initdb.d/init-with-charset.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  mysql_data:
